
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApplicationPerformance.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Appraisal
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Appraisal()
    {

        this.Goals = new HashSet<Goal>();

    }


    public int AppraisalID { get; set; }

    public Nullable<System.DateTime> AppraisalEndDate { get; set; }

    public Nullable<System.DateTime> AppraisalStartDate { get; set; }

    public Nullable<AppraisalStatus> AppraisalStatus { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Goal> Goals { get; set; }

}

}
