

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApplicationPerformance.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DatabasePMEntities : DbContext
{
    public DatabasePMEntities()
        : base("name=DatabasePMEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<SystemUser> SystemUsers { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<StoredRole> StoredRoles { get; set; }

    public virtual DbSet<Appraisal> Appraisals { get; set; }

    public virtual DbSet<Goal> Goals { get; set; }

    public virtual DbSet<SendEmail> SendEmails { get; set; }

    public virtual DbSet<Response> Responses { get; set; }

    public virtual DbSet<Evaluation> Evaluations { get; set; }

    public virtual DbSet<Objective> Objectives { get; set; }

}

}

