
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ApplicationPerformance.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SendEmail
{

    public int Id { get; set; }

    public string ToEmail { get; set; }

    public string EmailBody { get; set; }

    public string EmailSubject { get; set; }

    public string EmailCC { get; set; }

    public string EmailBCC { get; set; }

}

}
